name: Print Array Elements

on:
  workflow_dispatch:
    inputs:
      array:
        description: 'Comma-separated array'
        required: true

jobs:
  print_array_elements:
    runs-on: ubuntu-latest

    steps:
    - name: Print Array Elements
      run: |
        # Get the input array from the workflow input
        input_array="${{ github.event.inputs.array }}"
        
        # Split the input array into elements
        IFS=',' read -ra array_elements <<< "$input_array"
        
        # Print each element
        for element in "${array_elements[@]}"; do
          echo "Array element: $element"
        done
